variables:
  CODECOV_TOKEN: "zox65zv2QzBudAusBouB"

r-release:
  stage: test
  image: methodsconsultants/r-packaging:latest
  script:
    - Rscript -e 'install.packages(c("rARPACK"))'
    - R CMD build .
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --as-cran
  tags:
    - docker

