variables:
  CODECOV_TOKEN: "zox65zv2QzBudAusBouB"

before_script:
  - apt-get update -qq
  - apt-get install -y --no-install-recommends libcurl4-openssl-dev libssh2-1-dev libssl-dev git
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=TRUE

r-release:
  stage: test
  image: methodsconsultants/r-packaging:latest
  script:
    - Rscript -e 'install.packages(c("rARPACK"))'
    - R CMD build .
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --as-cran
  tags:
    - docker

