variables:
  CODECOV_TOKEN: "zox65zv2QzBudAusBouB"

r-release:
  stage: test
  image: rocker/tidyverse:latest
  script:
    - Rscript -e 'install.packages(c("devtools","testthat","roxygen2","rARPACK"))'
    - Rscript -e 'devtools::install_dev_deps()'
    - Rscript -e 'devtools::check()'
  tags:
    - docker

