variables:
  CODECOV_TOKEN: "zox65zv2QzBudAusBouB"

before_script:
  - apt-get update -qq
  - apt-get install -y --no-install-recommends libcurl4-openssl-dev libssh2-1-dev libssl-dev git
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - export _R_CHECK_CRAN_INCOMING_=FALSE
  - export _R_CHECK_FORCE_SUGGESTS_=TRUE

r-base:
  stage: test
  image: rocker/rstudio-stable:latest
  script:
    - Rscript -e 'install.packages(c("devtools", "roxygen2", "rARPACK"))'
    - Rscript -e 'devtools::install_dev_deps()'
    - Rscript -e 'devtools::check()'
  tags:
    - docker

r-devel:
  stage: test
  image: rocker/rstudio-stable:devel
  script:
    - RDscript -e 'install.packages(c("devtools", "roxygen2", "rARPACK"))'
    - RDscript -e 'devtools::install_dev_deps()'
    - RDscript -e 'devtools::check()'
  tags:
    - docker

r-oldrel:
  stage: test
  image: rocker/rstudio-stable:3
  script:
    - Rscript -e 'install.packages(c("devtools", "roxygen2", "rARPACK"))'
    - Rscript -e 'devtools::install_dev_deps()'
    - Rscript -e 'devtools::check()'
  tags:
    - docker
  allow_failure: true

r-packaging:
  stage: test
  image: methodsconsultants/r-packaging:latest
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
    - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran
  tags:
    - docker

